title: <p align="center"> Sheetal R </p>
logo: /assets/img/HPE_Logo.png

description:
  <p align="center">
  <a href="resume/Sheetal R.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sheetal-r-8b2b0843">LinkedIn</a> |
  <a href="https://github.com/Sheetal-R/">GitHub</a>
  
  <br>   
   <br>
  </p>



theme: jekyll-theme-minimal
